### ISSUE TITLE
Possibility to change the marker panel 

### ISSUE THREAD

**Issue by cdub3575** [sun-huangqingbo/multiplexed-image-annotator#1]
Hello,

I am very interested by your method, I was wondering if it is possible to change the marker panel and corresponding cell types. Our panel is a bit different from the possibilities presented in the article. For instance we don't have CD20 and Vimentin but other markers for B cells and Stroma cells.

Thank you in advance,

Charlotte

**Comment by sun-huangqingbo** [comment]
You can try those images with other B cell and stroma cell markers, but write "CD20" and "Vimentin" in the marker file instead of the real names of those two markers. This trick is to fake the marker-matching modules. Please do check the annotation later since our models are not intentionally trained for the new markers, though I expect the models can still work.

**Comment by cdub3575** [comment]
Ok Thank you very much ! And if we have two markers instead of one for a celltype, what do you recommand ?

**Comment by sun-huangqingbo** [comment]
You may want to try each of them and see which is better, or simply merge their results by finding the agreements.
